/**
 * SEO — per-route <title> / <meta> / canonical / hreflang management.
 *
 * Residata is a SPA, so the same index.html is served for every URL.
 * Search engines do execute JS (Googlebot since 2019), so updating the
 * DOM <head> on route change DOES propagate into Google's index. But:
 *   · The static defaults in index.html matter for crawlers that don't
 *     execute JS (Perplexity's own crawler, some lightweight bots, and
 *     for the first paint before React hydrates).
 *   · The dynamic updates here override those defaults once the user
 *     actually lands on a specific route.
 *
 * Design choice — no external dep (no react-helmet):
 *   The app's dep footprint is deliberately tiny (4 runtime deps).
 *   A ~30-line useEffect hook does the job without adding 50 kB of
 *   library for a single feature.
 *
 * What we set per-route:
 *   · document.title
 *   · meta[name=description]
 *   · meta[name=keywords]
 *   · link[rel=canonical]
 *   · meta[property=og:title|og:description|og:url|og:locale]
 *   · meta[name=twitter:title|twitter:description]
 *   · html[lang]
 *   · link[rel=alternate][hreflang=en|sk|x-default]
 *
 * How to add a new route: extend SEO_BY_PAGE with an entry keyed on the
 * internal page name (see src/lib/routing.js). Copy is in both
 * languages; the hook picks the right one based on `lang` prop.
 */

// Production base — used for og:url / canonical. Precedence:
//   1. VITE_SITE_BASE env  → pin the canonical domain in prod (e.g. set
//      VITE_SITE_BASE=https://residata.sk in Vercel when the domain goes live).
//   2. window.location.origin → self-referential canonical on whatever domain
//      actually serves the app (never wrong; avoids leaking the staging URL).
//   3. the staging fallback → SSR/first-paint before the origin is known.
// Single-sourced so a custom-domain switch is one env var, not a code sweep.
// NOTE: the static index.html + sitemap.xml are generated by
// scripts/generate-static-content.mjs, which reads the same SITE_BASE env.
import { PUBLIC_LANGS } from "./locale";
import { currentPriceStrings } from "./pricing";

export const SITE_BASE =
  (typeof import.meta !== "undefined" && import.meta.env && import.meta.env.VITE_SITE_BASE) ||
  (typeof window !== "undefined" && window.location && window.location.origin) ||
  "https://residata-gamma.vercel.app";

/**
 * SEO metadata per (page, lang). Kept together so the translation burden
 * of adding a route is visible — no split copy surfaces.
 * Keywords lean on what Slovak buyers actually type into Google:
 * "novostavby Bratislava", "ceny bytov", "predaj bytov novostavba", etc.
 * English keywords target cross-border investors + bank/valuer
 * terminology ("property market data Slovakia", "absorption rate").
 */
const SEO_BY_PAGE = {
  Home: {
    path: "/",
    en: {
      title: "Residata — New-Build Market Intelligence for Bratislava",
      description: "Every new residential development in Bratislava, structured and refreshed daily. Pricing, availability, absorption, and trends — built for developers, banks, valuers, and investors.",
      keywords: "Bratislava real estate, new-build market data, residential market intelligence, absorption rate, property market Slovakia, €/m² trends",
    },
    sk: {
      title: "Residata — Dátový prehľad trhu novostavieb Bratislava",
      description: "Každý aktívny projekt novostavby v Bratislave na jednom mieste. Ceny, dostupnosť, rýchlosť predaja a trendy — aktualizované každý deň. Pre developerov, banky, odhadcov a investorov.",
      keywords: "novostavby Bratislava, trh novostavieb, ceny bytov, market intelligence, dáta nehnuteľnosti, €/m² trendy, rýchlosť predaja",
    },
  },
  Live: {
    path: "/live",
    en: {
      title: "Live Dashboard — Residata | Bratislava New-Build Market",
      description: "Explore every active new-build residential project in Bratislava: units available, sold percentage, €/m² by project and district, and sell-out watch list.",
      keywords: "live dashboard Bratislava real estate, new-build projects, units available, sold percentage, €/m² by project",
    },
    sk: {
      title: "Live dashboard — Residata | Trh novostavieb Bratislava",
      description: "Pozrite si každý aktívny projekt novostavby v Bratislave: voľné byty, percento predaja, €/m² podľa projektu a okresu, sledovanie blížiacich sa sell-out-ov.",
      keywords: "live dashboard Bratislava, novostavby projekty, voľné byty, % predaja, €/m² podľa projektu",
    },
  },
  "Use Cases": {
    path: "/use-cases",
    en: {
      title: "Use Cases — Residata | Market Data for Developers, Banks, Investors",
      description: "How developers price new launches, how banks source comparables, how investors spot opportunities, and how consultants build presentation-ready market reports. All from a single dataset.",
      keywords: "real estate data use cases, developer pricing, bank comparables, valuation data, investor deal sourcing, consultant market report",
    },
    sk: {
      title: "Využitie — Residata | Trhové dáta pre developerov, banky, investorov",
      description: "Ako developeri oceňujú nové projekty, ako banky hľadajú komparatívy, ako investori vyhľadávajú príležitosti a ako konzultanti pripravujú prehľady trhu — všetko z jednej dátovej sady.",
      keywords: "využitie realitných dát, oceňovanie developer, bankové komparatívy, odhad nehnuteľnosti, investor deal flow",
    },
  },
  Data: {
    path: "/sample",
    en: {
      title: "What We Deliver — Residata | Sample Market Intelligence Output",
      description: "See what a Residata delivery actually looks like — unit-level data, market insights with directional signals (sell-out forecasts, pricing tension, scarcity clock), and the full data schema.",
      keywords: "real estate data sample, market intelligence report, unit-level data schema, absorption forecast, sell-out watch",
    },
    sk: {
      title: "Čo dostanete — Residata | Ukážka výstupu",
      description: "Pozrite si ako vyzerá výstup Residata — dáta na úrovni bytu, insighty s predpoveďami (sell-out forecast, cenová tenzia, scarcity clock) a kompletná schéma dát.",
      keywords: "ukážka realitných dát, trhový report, dáta na úrovni bytu, schéma dát, sell-out predpoveď",
    },
  },
  Pricing: {
    path: "/pricing",
    en: {
      title: "Pricing — Residata | __PRICE__ / month",
      description: "Full access to the Slovak & Czech new-build market dataset for __PRICE__ / month — summer early-access rate (regular __ANCHOR__). 7-day free trial, cancel anytime.",
      keywords: "Residata pricing, real estate data pricing, market intelligence subscription, __PRICE__ monthly",
    },
    sk: {
      title: "Cenník — Residata | __PRICE__ / mesiac",
      description: "Plný prístup ku kompletným dátam novostavieb na Slovensku a v Česku za __PRICE__ / mesiac — letná úvodná cena (bežne __ANCHOR__). 7-dňová skúšobná verzia zdarma, zrušenie kedykoľvek.",
      keywords: "Residata cenník, ceny dát nehnuteľnosti, market intelligence predplatné, __PRICE__ mesačne",
    },
  },
  Contact: {
    path: "/contact",
    en: {
      title: "Contact — Residata",
      description: "Get in touch with Residata — for sample reports, custom delivery, or enterprise pricing. Email: info@residata.eu",
      keywords: "Residata contact, real estate data contact, custom market report Bratislava",
    },
    sk: {
      title: "Kontakt — Residata",
      description: "Kontaktujte Residata — pre ukážkový report, custom dodávku alebo enterprise ceny. Email: info@residata.eu",
      keywords: "Residata kontakt, dáta nehnuteľnosti kontakt, custom report Bratislava",
    },
  },
  // F-051 legal pages — noindex because they don't earn search traffic
  // and indexing them would just dilute Google's view of what Residata is.
  // Each title in-page is set via useDocumentTitle inside LegalPages.jsx;
  // these entries make the SEO sweep (open graph, robots, hreflang) consistent.
  Privacy: {
    path: "/privacy",
    en: {
      title: "Privacy Policy · Residata",
      description: "How Residata handles personal data, third parties involved, retention, and user rights under GDPR.",
    },
    sk: {
      title: "Ochrana osobných údajov · Residata",
      description: "Ako Residata spracúva osobné údaje, ktoré tretie strany sú zapojené, doba uchovávania a vaše práva podľa GDPR.",
    },
    noindex: true,
  },
  Imprint: {
    path: "/imprint",
    en: {
      title: "Imprint · Residata",
      description: "Information about the operator of the Residata website.",
    },
    sk: {
      title: "Impressum · Residata",
      description: "Informácie o prevádzkovateľovi webu Residata.",
    },
    noindex: true,
  },
  Terms: {
    path: "/terms",
    en: {
      title: "Terms of Service · Residata",
      description: "The terms governing use of Residata — access, subscriptions, acceptable use, and liability.",
    },
    sk: {
      title: "Obchodné podmienky · Residata",
      description: "Podmienky používania Residata — prístup, predplatné, prijateľné použitie a zodpovednosť.",
    },
    noindex: true,
  },
};

/**
 * Per-country SEO copy overrides.
 *
 * The site is ONE SPA with a client-side country switcher (no per-country
 * URLs), so canonical / hreflang / og:url stay per-route and are NOT touched
 * here — only the human-facing title / description / keywords (and the
 * og:* / twitter:* tags that derive from them) get localized to the selected
 * market.
 *
 * Mirrors the COUNTRY_COPY pattern in src/App.jsx: SK has NO entry, so
 * applySeo(..., 'SK') (and any unknown country) returns the base copy
 * byte-identical. A country block is a lang-keyed list of literal
 * find→replace rules applied to the resolved title/description/keywords.
 *
 * Why find→replace rather than a full per-route copy duplicate: the SK copy
 * is the single source of truth, so adding/editing a route doesn't require
 * re-typing every string for every market (which inevitably drifts). The
 * rules are ordered most-specific-first so multi-word phrases win before the
 * bare city/country token (e.g. "Bratislava real estate" before "Bratislava").
 *
 * To add a market: add a block keyed by ISO code with `en`/`sk` rule lists.
 */
const SEO_COUNTRY_OVERRIDES = {
  CZ: {
    en: [
      ["novostavby Bratislava", "novostavby Praha"],
      ["Bratislava real estate", "Prague real estate"],
      ["property market Slovakia", "property market Czechia"],
      ["market data Slovakia", "market data Czechia"],
      ["Bratislava", "Prague"],
      ["Slovakia", "Czechia"],
    ],
    sk: [
      ["novostavby Bratislava", "novostavby Praha"],
      ["v Bratislave", "v Prahe"],
      ["Bratislava", "Praha"],
      ["Slovensko", "Česko"],
    ],
  },
  // "all" = combined SK+CZ view (the default country). Only the visible page
  // TITLES are broadened off Bratislava-only; descriptions/keywords keep the
  // base copy (Bratislava keywords still carry SEO value). Precise full-phrase
  // rules → no bare-token double-replacement risk.
  all: {
    en: [
      ["New-Build Market Intelligence for Bratislava", "New-Build Market Intelligence for Slovakia & Czechia"],
      ["Bratislava New-Build Market", "Slovak & Czech New-Build Market"],
    ],
    sk: [
      ["Dátový prehľad trhu novostavieb Bratislava", "Dátový prehľad trhu novostavieb — Slovensko a Česko"],
      ["Trh novostavieb Bratislava", "Trh novostavieb — Slovensko a Česko"],
    ],
  },
};

/**
 * Apply a country's find→replace rules to a single copy string. Returns the
 * input unchanged when there's no override (SK / unknown country / no string).
 */
function applyCountryRules(value, rules) {
  if (!value || !rules) return value;
  let out = value;
  for (const [from, to] of rules) out = out.split(from).join(to);
  return out;
}

/**
 * Localize a resolved SEO entry (title/description/keywords) for the selected
 * country. Only these three fields are market-named; og:* / twitter:* derive
 * from title/description downstream, so they inherit the override for free.
 * Canonical / hreflang / og:url / og:locale / robots / html[lang] are left to
 * the per-route logic and are never altered here.
 */
function localizeSeoForCountry(meta, lang, country) {
  const rules = SEO_COUNTRY_OVERRIDES[country]?.[lang === "sk" ? "sk" : "en"];
  if (!rules) return meta;
  return {
    ...meta,
    title: applyCountryRules(meta.title, rules),
    description: applyCountryRules(meta.description, rules),
    keywords: applyCountryRules(meta.keywords, rules),
  };
}

/**
 * Upsert a <meta> by name OR property. Creates the tag if missing. This
 * avoids fragile Element.setAttribute chains scattered through the hook.
 */
function setMeta(attr, key, value) {
  let el = document.head.querySelector(`meta[${attr}="${key}"]`);
  if (!el) {
    el = document.createElement("meta");
    el.setAttribute(attr, key);
    document.head.appendChild(el);
  }
  el.setAttribute("content", value);
}

function setLink(rel, href, hreflang) {
  // hreflang lets us update the right alternate without touching the others
  const sel = hreflang
    ? `link[rel="${rel}"][hreflang="${hreflang}"]`
    : `link[rel="${rel}"]`;
  let el = document.head.querySelector(sel);
  if (!el) {
    el = document.createElement("link");
    el.setAttribute("rel", rel);
    if (hreflang) el.setAttribute("hreflang", hreflang);
    document.head.appendChild(el);
  }
  el.setAttribute("href", href);
}

/**
 * Resolve the SEO entry for a given internal page name. Project detail
 * and app/platform pages fall through to a generic entry (we don't want
 * each dynamic project page minting a unique index-worthy title — those
 * are gated content).
 */
function resolvePageSeo(page, lang) {
  // Project detail — per-project page, we just render a generic title
  // (individual project data is behind login, not useful as SEO target).
  if (typeof page === "string" && page.startsWith("Project:")) {
    return {
      path: "/live",
      ...(lang === "sk"
        ? { title: "Detail projektu — Residata", description: "Detailné dáta konkrétneho projektu novostavby v Bratislave.", keywords: "novostavba detail Bratislava" }
        : { title: "Project Detail — Residata", description: "Detailed data on a specific new-build residential project in Bratislava.", keywords: "new-build project detail Bratislava" }),
      noindex: true,
    };
  }
  // Platform / app — private, don't index
  if (typeof page === "string" && page.startsWith("App:")) {
    return {
      path: "/app",
      ...(lang === "sk"
        ? { title: "Platforma — Residata", description: "Prihlásená platforma Residata." }
        : { title: "Platform — Residata", description: "Residata authenticated platform." }),
      noindex: true,
    };
  }
  const entry = SEO_BY_PAGE[page];
  if (!entry) return null;
  // Preserve top-level entry-wide flags (e.g. noindex) alongside the
  // language-specific copy. Without this spread the noindex flag set on
  // Privacy/Imprint entries was being dropped, so applySeo wrote
  // `index, follow` instead of `noindex, nofollow` to <meta robots>.
  return {
    path: entry.path,
    noindex: entry.noindex,
    ...entry[lang === "sk" ? "sk" : "en"],
  };
}

/**
 * Apply SEO metadata to the document for a given (page, lang, country) tuple.
 * Called from App.jsx inside a useEffect so it fires on every navigation or
 * country switch.
 *
 * `country` only localizes the visible copy (title / description / keywords →
 * og:* / twitter:*). The canonical / hreflang / og:url / og:locale / robots /
 * html[lang] logic is per-route and country-agnostic by design (one SPA, no
 * per-country URLs). SK / unknown country → base copy, byte-identical.
 */
export function applySeo(page, lang, country) {
  if (typeof document === "undefined") return;
  const resolved = resolvePageSeo(page, lang);
  if (!resolved) return;
  // Shallow copy so the __PRICE__/__ANCHOR__ substitution below never mutates the
  // shared SEO_DATA source (which would bake a one-time price into the tokens).
  const meta = { ...localizeSeoForCountry(resolved, lang, country) };

  // Single source of truth for price = public.pricing_config (admin Pricing
  // editor). Substitute the live value into any tokens so SEO meta follows the
  // editor automatically — never hardcode a price string in this file.
  {
    const { price, anchor } = currentPriceStrings();
    for (const k of ["title", "description", "keywords"]) {
      if (typeof meta[k] === "string") {
        meta[k] = meta[k].split("__PRICE__").join(price).split("__ANCHOR__").join(anchor);
      }
    }
  }

  const url = SITE_BASE + meta.path;
  const locale = { sk: "sk_SK", cs: "cs_CZ" }[lang] || "en_US";

  // <html lang> — important for accessibility + hreflang signals. Reflects the
  // SELECTED language (en|sk|cs), even though untranslated copy falls back to
  // English — by the time CZ is public the copy is authored in Czech.
  document.documentElement.setAttribute("lang", { sk: "sk", cs: "cs" }[lang] || "en");

  // Title + primary description
  document.title = meta.title;
  setMeta("name", "description", meta.description);
  if (meta.keywords) setMeta("name", "keywords", meta.keywords);

  // Robots control — private pages are noindex
  setMeta("name", "robots", meta.noindex
    ? "noindex, nofollow"
    : "index, follow, max-image-preview:large, max-snippet:-1");

  // Canonical URL
  setLink("canonical", url);

  // hreflang — tell Google which language versions exist at this same URL
  // (we don't have /sk prefix — language is state-driven). Driven by PUBLIC_LANGS
  // so we never advertise a language the switcher hides (e.g. Czech pre-launch).
  // The x-default points to the primary (English).
  PUBLIC_LANGS.forEach((code) => setLink("alternate", url, code));
  setLink("alternate", url, "x-default");

  // Open Graph
  setMeta("property", "og:title", meta.title);
  setMeta("property", "og:description", meta.description);
  setMeta("property", "og:url", url);
  setMeta("property", "og:locale", locale);
  setMeta("property", "og:site_name", "Residata");
  setMeta("property", "og:type", "website");

  // Twitter / X
  setMeta("name", "twitter:card", "summary_large_image");
  setMeta("name", "twitter:title", meta.title);
  setMeta("name", "twitter:description", meta.description);
}
