"""Turn a rendered issue into the row `public.articles` expects.

WHY THIS EXISTS
    The CMS at /app/articles stores an article as `title`/`perex`/`method` as
    {sk, en} pairs and `blocks` as an array of typed blocks. Rebuilding that by
    hand from a finished draft is transcription, and transcription is where a
    figure changes between the text and the page. This does it mechanically, so
    the row and the draft cannot say different things.

    It prints JSON. It does NOT write to the database — publishing is a person's
    decision, and the row it prints is pasted (or inserted) deliberately.

USAGE
    python3 src/content/analyzy/drafts/to_cms.py mapa-novostavieb-2026-09 > row.json

WHAT IT MAPS
    `# …`                 → title
    <!--PEREX …-->        → perex (index card + SEO description)
    <!--METHOD …-->       → method (the boxed "Metodika" the page always renders)
    first paragraph       → a `lead` block
    `## …`                → an `h2` block
    `![alt](src)` + `*…*` → a `figure` block, with the -en.svg as `srcEn`
    `| … |` table         → a `table` block
    everything else       → `p` blocks
    `---`                 → dropped; the page has its own rhythm
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LANGS = ("sk", "en")

#: set by main() once it knows whether an English draft exists; _blocks() needs
#: it when it decides which chart a figure points at.
SK_ONLY = [False]


def _plain(text: str) -> str:
    r"""Strip the markdown the draft carries for a human reader.

    The CMS renders every block as TEXT, not markdown — `p`, `h2`, table cells
    and captions all go through React as plain strings. So `**Q3 2026**` in the
    draft printed as literal asterisks in the table on the live page, and `\*`
    at the start of the footnote printed its backslash. The draft keeps its
    markdown, because that is what makes it readable as a file; this is the one
    place it is taken off.
    """
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)   # bold
    text = re.sub(r"(?<!\w)\*(.+?)\*(?!\w)", r"\1", text)  # italics
    return text.replace("\\*", "*").replace("\\_", "_").strip()


def _section(text: str, name: str) -> str:
    m = re.search(rf"<!--{name}\n(.*?)\n-->", text, re.S)
    return m.group(1).strip() if m else ""


def _blocks(text: str) -> list[dict]:
    """Parse one language's markdown into ordered blocks."""
    # Everything between the sentinels is for the human reading the draft: the
    # long method section, which the PAGE renders from the `method` column in its
    # own box. Leaving it in `blocks` too would print the methodology twice.
    body = re.sub(r"<!--CMS-SKIP-START-->.*?<!--CMS-SKIP-END-->", "", text, flags=re.S)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S).strip()
    lines = body.split("\n")
    out: list[dict] = []
    i = 0
    seen_title = False
    table: list[str] = []

    def flush_table():
        nonlocal table
        if not table:
            return
        head = [_plain(c) for c in table[0].strip("|").split("|")]
        rows = [[_plain(c) for c in r.strip("|").split("|")] for r in table[2:]]
        out.append({"type": "table", "head": head, "rows": rows})
        table = []

    while i < len(lines):
        line = lines[i].rstrip()
        if line.startswith("|"):
            table.append(line)
            i += 1
            continue
        flush_table()
        if not line or line == "---":
            i += 1
            continue
        if line.startswith("# "):
            seen_title = True
            i += 1
            continue
        if line.startswith("## "):
            out.append({"type": "h2", "text": _plain(line[3:])})
            i += 1
            continue
        if line.startswith("!["):
            m = re.match(r"!\[(.*?)\]\((.*?)\)", line)
            caption = ""
            if i + 1 < len(lines) and lines[i + 1].startswith("*"):
                caption = _plain(lines[i + 1])
                i += 1
            src = m.group(2)
            out.append({
                "type": "figure", "alt": _plain(m.group(1)), "caption": caption,
                # One chart per language, already generated by market_report.
                "src": src.replace("-en.svg", ".svg"),
                "srcEn": (src.replace("-en.svg", ".svg") if SK_ONLY[0]
                          else src.replace(".svg", "-en.svg").replace("-en-en", "-en")),
            })
            i += 1
            continue
        # A run of "- " lines is ONE bullets block, not N paragraphs each
        # starting with a stray dash. Insights.jsx has rendered `bullets` all
        # along; this file simply never emitted one, so a summary list came out
        # as literal markdown on the page.
        if line.startswith("- ") and seen_title:
            items = []
            while i < len(lines) and lines[i].rstrip().startswith("- "):
                items.append(_plain(lines[i].rstrip()[2:]))
                i += 1
            out.append({"type": "bullets", "items": items})
            continue
        # The eyebrow line above the headline is furniture the page draws itself.
        if not seen_title:
            i += 1
            continue
        out.append({"type": "p", "text": _plain(line)})
        i += 1
    flush_table()

    # The first paragraph after the headline is the lede, and the page styles it.
    for b in out:
        if b["type"] == "p":
            b["type"] = "lead"
            break
    return out


def _pair(a: dict | str, b: dict | str) -> dict:
    return {"sk": a, "en": b}


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    slug = sys.argv[1]
    texts = {}
    for lang in LANGS:
        p = HERE / f"{slug}.{lang}.md"
        if p.exists():
            texts[lang] = p.read_text(encoding="utf-8")
    if "sk" not in texts:
        print(f"missing {HERE / f'{slug}.sk.md'}", file=sys.stderr)
        return 1
    # An issue published in Slovak only. Both sides of every {sk, en} pair get
    # the Slovak text, so t() serves it to either reader — which is honest:
    # there is no English issue, rather than a half-translated one.
    sk_only = "en" not in texts
    SK_ONLY[0] = sk_only
    if sk_only:
        texts["en"] = texts["sk"]
        print(f"note: no {slug}.en.md — publishing Slovak to both languages",
              file=sys.stderr)

    parsed = {lang: _blocks(texts[lang]) for lang in LANGS}
    if len(parsed["sk"]) != len(parsed["en"]):
        print(f"REFUSING: sk has {len(parsed['sk'])} blocks and en has "
              f"{len(parsed['en'])} — they must line up one for one", file=sys.stderr)
        return 1

    blocks = []
    for bs, be in zip(parsed["sk"], parsed["en"]):
        if bs["type"] != be["type"]:
            print(f"REFUSING: block types diverge ({bs['type']} vs {be['type']})",
                  file=sys.stderr)
            return 1
        if bs["type"] == "figure":
            blocks.append({"type": "figure", "src": bs["src"], "srcEn": bs["srcEn"],
                           "alt": _pair(bs["alt"], be["alt"]),
                           "caption": _pair(bs["caption"], be["caption"])})
        elif bs["type"] == "table":
            # 🔴 ROW CELLS DIFFER BY LANGUAGE AND USED NOT TO TRAVEL. Only the
            # Slovak rows were kept, so every English table on the site printed
            # Slovak decimal commas — "28,6 %" where an English reader expects
            # "28.6 %". A cell that is the same in both stays a plain string, so
            # a table of pure numbers does not double in size; only the cells
            # that genuinely differ become a {sk, en} pair, which t() resolves.
            if len(bs["rows"]) != len(be["rows"]):
                print(f"REFUSING: a table has {len(bs['rows'])} rows in sk and "
                      f"{len(be['rows'])} in en", file=sys.stderr)
                return 1
            rows = [[x if x == y else _pair(x, y) for x, y in zip(rs, re_)]
                    for rs, re_ in zip(bs["rows"], be["rows"])]
            blocks.append({"type": "table",
                           "head": _pair(bs["head"], be["head"]),
                           "rows": rows})
        elif bs["type"] == "bullets":
            # A bullets block carries `items`, not `text`, and the two languages
            # must line up item for item — otherwise the English reader gets the
            # Slovak list's fourth point under their third.
            if len(bs["items"]) != len(be["items"]):
                print(f"REFUSING: a bullets block has {len(bs['items'])} items in "
                      f"sk and {len(be['items'])} in en", file=sys.stderr)
                return 1
            blocks.append({"type": "bullets",
                           "items": [_pair(x, y)
                                     for x, y in zip(bs["items"], be["items"])]})
        else:
            blocks.append({"type": bs["type"], "text": _pair(bs["text"], be["text"])})

    title = {lang: _plain(re.search(r"^# (.+)$", texts[lang], re.M).group(1))
             for lang in LANGS}
    row = {
        "slug": slug,
        # The date the figures were taken, straight from the report — never today's
        # date, because a row created tomorrow would then claim tomorrow's data.
        "article_date": json.loads(
            (HERE.parent / "data" / f"report-{slug}.json").read_text(encoding="utf-8"))["asOf"],
        "published": False,
        "title": title,
        "perex": {lang: _plain(_section(texts[lang], "PEREX")) for lang in LANGS},
        "method": {lang: _plain(_section(texts[lang], "METHOD")) for lang in LANGS},
        # How far the data actually goes. NULL here is a failure in the nightly
        # integrity_check, not a blank: an issue previewed before its period
        # closed carries a projection, and the check exists so the regeneration
        # that turns it into a measurement cannot be quietly forgotten.
        "figures_measured_through": json.loads(
            (HERE.parent / "data" / f"report-{slug}.json").read_text(encoding="utf-8"))["asOf"],
        "og_image": f"/analyzy/og-{slug}.png",
        "blocks": blocks,
    }
    json.dump(row, sys.stdout, ensure_ascii=False, indent=1)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
