"""Turn a rendered issue into the row `public.articles` expects.

WHY THIS EXISTS
    The CMS at /app/articles stores an article as `title`/`perex`/`method` as
    {sk, en} pairs and `blocks` as an array of typed blocks. Rebuilding that by
    hand from a finished draft is transcription, and transcription is where a
    figure changes between the text and the page. This does it mechanically, so
    the row and the draft cannot say different things.

    It prints JSON. It does NOT write to the database — publishing is a person's
    decision, and the row it prints is pasted (or inserted) deliberately.

USAGE
    python3 src/content/analyzy/drafts/to_cms.py mapa-novostavieb-2026-09 > row.json

WHAT IT MAPS
    `# …`                 → title
    <!--PEREX …-->        → perex (index card + SEO description)
    <!--METHOD …-->       → method (the boxed "Metodika" the page always renders)
    first paragraph       → a `lead` block
    `## …`                → an `h2` block
    `![alt](src)` + `*…*` → a `figure` block, with the -en.svg as `srcEn`
    `| … |` table         → a `table` block
    everything else       → `p` blocks
    `---`                 → dropped; the page has its own rhythm
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
LANGS = ("sk", "en")


def _section(text: str, name: str) -> str:
    m = re.search(rf"<!--{name}\n(.*?)\n-->", text, re.S)
    return m.group(1).strip() if m else ""


def _blocks(text: str) -> list[dict]:
    """Parse one language's markdown into ordered blocks."""
    # Everything between the sentinels is for the human reading the draft: the
    # long method section, which the PAGE renders from the `method` column in its
    # own box. Leaving it in `blocks` too would print the methodology twice.
    body = re.sub(r"<!--CMS-SKIP-START-->.*?<!--CMS-SKIP-END-->", "", text, flags=re.S)
    body = re.sub(r"<!--.*?-->", "", body, flags=re.S).strip()
    lines = body.split("\n")
    out: list[dict] = []
    i = 0
    seen_title = False
    table: list[str] = []

    def flush_table():
        nonlocal table
        if not table:
            return
        head = [c.strip() for c in table[0].strip("|").split("|")]
        rows = [[c.strip() for c in r.strip("|").split("|")] for r in table[2:]]
        out.append({"type": "table", "head": head, "rows": rows})
        table = []

    while i < len(lines):
        line = lines[i].rstrip()
        if line.startswith("|"):
            table.append(line)
            i += 1
            continue
        flush_table()
        if not line or line == "---":
            i += 1
            continue
        if line.startswith("# "):
            seen_title = True
            i += 1
            continue
        if line.startswith("## "):
            out.append({"type": "h2", "text": line[3:].strip()})
            i += 1
            continue
        if line.startswith("!["):
            m = re.match(r"!\[(.*?)\]\((.*?)\)", line)
            caption = ""
            if i + 1 < len(lines) and lines[i + 1].startswith("*"):
                caption = lines[i + 1].strip().strip("*")
                i += 1
            src = m.group(2)
            out.append({
                "type": "figure", "alt": m.group(1), "caption": caption,
                # One chart per language, already generated by market_report.
                "src": src.replace("-en.svg", ".svg"),
                "srcEn": src.replace(".svg", "-en.svg").replace("-en-en", "-en"),
            })
            i += 1
            continue
        # The eyebrow line above the headline is furniture the page draws itself.
        if not seen_title:
            i += 1
            continue
        out.append({"type": "p", "text": line})
        i += 1
    flush_table()

    # The first paragraph after the headline is the lede, and the page styles it.
    for b in out:
        if b["type"] == "p":
            b["type"] = "lead"
            break
    return out


def _pair(a: dict | str, b: dict | str) -> dict:
    return {"sk": a, "en": b}


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    slug = sys.argv[1]
    texts = {}
    for lang in LANGS:
        p = HERE / f"{slug}.{lang}.md"
        if not p.exists():
            print(f"missing {p}", file=sys.stderr)
            return 1
        texts[lang] = p.read_text(encoding="utf-8")

    parsed = {lang: _blocks(texts[lang]) for lang in LANGS}
    if len(parsed["sk"]) != len(parsed["en"]):
        print(f"REFUSING: sk has {len(parsed['sk'])} blocks and en has "
              f"{len(parsed['en'])} — they must line up one for one", file=sys.stderr)
        return 1

    blocks = []
    for bs, be in zip(parsed["sk"], parsed["en"]):
        if bs["type"] != be["type"]:
            print(f"REFUSING: block types diverge ({bs['type']} vs {be['type']})",
                  file=sys.stderr)
            return 1
        if bs["type"] == "figure":
            blocks.append({"type": "figure", "src": bs["src"], "srcEn": bs["srcEn"],
                           "alt": _pair(bs["alt"], be["alt"]),
                           "caption": _pair(bs["caption"], be["caption"])})
        elif bs["type"] == "table":
            blocks.append({"type": "table",
                           "head": _pair(bs["head"], be["head"]),
                           "rows": bs["rows"]})
        else:
            blocks.append({"type": bs["type"], "text": _pair(bs["text"], be["text"])})

    title = {lang: re.search(r"^# (.+)$", texts[lang], re.M).group(1).strip()
             for lang in LANGS}
    row = {
        "slug": slug,
        # The date the figures were taken, straight from the report — never today's
        # date, because a row created tomorrow would then claim tomorrow's data.
        "article_date": json.loads(
            (HERE.parent / "data" / f"report-{slug}.json").read_text(encoding="utf-8"))["asOf"],
        "published": False,
        "title": title,
        "perex": {lang: _section(texts[lang], "PEREX") for lang in LANGS},
        "method": {lang: _section(texts[lang], "METHOD") for lang in LANGS},
        "og_image": f"/analyzy/og-{slug}.png",
        "blocks": blocks,
    }
    json.dump(row, sys.stdout, ensure_ascii=False, indent=1)
    print()
    return 0


if __name__ == "__main__":
    sys.exit(main())
